ebook_metadata:
  title: ༄༅། །ཆོས་ཐམས་ཅད་ཀྱི་སྙིང་པོ་ཕྱག་རྒྱ་ཆེན་པོའི་དོན་ཡང་དག་པ་རབ་ཏུ་གསལ་བར་བྱེད་པ་དྲི་མ་མེད་པའི་སྒྲོན་མ་ཞེས་བྱ་བ་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། མཁས་གྲུབ་ཆེན་པོ་རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།
  sku: TSD-TSE-03
  layers:
  - book_title
  - author
  - chapter_title
  - yigchung
web_metadata:
  title:
    en: The Lamp of Mahamudra:A Clear and Accurate Presentation of Mahamudra, the
      Essense of All Phenomena
    bo: ཆོས་ཐམས་ཅད་ཀྱི་སྙིང་པོ་ཕྱག་རྒྱ་ཆེན་པོའི་དོན་ཡང་དག་པ་རབ་ཏུ་གསལ་བར་བྱེད་པ་དྲི་མ་མེད་པའི་སྒྲོན་མ་ཞེས་བྱ་བ་བཞུགས་སོ།
  collection:
    en: Tsele Natsok Rangdrol Series–  Book 3
    bo: རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།–  དེབ། ༣
  author:
    en: Tsele Natsok Rangdrol
    bo: རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།
  pusblisher:
    en: Tsadra Foundation Publishing
    bo: ཙཱ་འདྲ་ཐེབས་རྩ་ཚོགས་པ།
  sku: TSD-TSE-03
  category:
    en: Mahamudra
    bo: ཕྱག་རྒྱ་ཆེན་པོ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: TSD-TSE-03.epub
  description:
    en: ''
    bo: ''
